spring:
  application:
    name: medical-record-service

  config:
    import: optional:configserver:http://capstone-config-server:8888

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka/