spring:
  application:
    name: notification-service

  cloud:
    config:
      uri: http://config-server:8888

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka/