version: '3'

services:
  rabbit:
    image: rabbitmq:3-management

    ports:
      - "15672:15672"
      - "5672:5672"


  user-db:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'

    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "localhost", "-p", "5432", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3

    environment:
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: capstone
      POSTGRES_DB: user_db

    volumes:
      - user_data:/var/lib/postgresql/data

  appointment-db:
    image: postgres:15
    restart: always
    ports:
      - '5433:5432'

    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "localhost", "-p", "5432", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3

    environment:
      POSTGRES_USER: appointment
      POSTGRES_PASSWORD: capstone
      POSTGRES_DB: appointment

    volumes:
      - appointment_data:/var/lib/postgresql/data

  expense-db:
    image: postgres:15
    restart: always
    ports:
      - '5435:5432'

    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "localhost", "-p", "5432", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3

    environment:
      POSTGRES_USER: expense
      POSTGRES_PASSWORD: capstone
      POSTGRES_DB: expense

    volumes:
      - expense_data:/var/lib/postgresql/data

  medical-record-db:
    image: postgres:15
    restart: always
    ports:
      - '5434:5432'

    healthcheck:
      test: [ "CMD", "pg_isready", "-h", "localhost", "-p", "5432", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3

    environment:
      POSTGRES_USER: medical-record
      POSTGRES_PASSWORD: capstone
      POSTGRES_DB: medical-record

    volumes:
      - medical-record_data:/var/lib/postgresql/data


  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile

    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "--proxy=off", "http://localhost:8888/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 4


    ports:
      - "8888:8888"


  registry-service:
    build:
      context: ./registry-service
      dockerfile: Dockerfile

    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "--proxy=off", "http://localhost:8761/actuator/health"]
      interval: 15s
      timeout: 10s
      retries: 4

    ports:
      - "8761:8761"

  user:
    build:
      context: ./user-service
      dockerfile: Dockerfile

    ports:
      - "8080:8080"

    depends_on:
      config-server:
        condition: service_healthy
      registry-service:
        condition: service_healthy
      user-db:
        condition: service_healthy


  medical-record:
    build:
      context: ./medical-record-service
      dockerfile: Dockerfile

    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "--proxy=off", "http://localhost:8082/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 4

    ports:
      - "8082:8082"

    depends_on:
      config-server:
        condition: service_healthy
      registry-service:
        condition: service_healthy
      medical-record-db:
        condition: service_healthy


  appointment:
    build:
      context: ./appointment-service
      dockerfile: Dockerfile

    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "--proxy=off", "http://localhost:8083/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 4

    ports:
      - "8083:8083"

    depends_on:
      config-server:
        condition: service_healthy
      registry-service:
        condition: service_healthy
      appointment-db:
        condition: service_healthy

  expense:
    build:
      context: ./expense-service
      dockerfile: Dockerfile

    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "--proxy=off", "http://localhost:8084/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 4

    ports:
      - "8084:8084"

    depends_on:
      config-server:
        condition: service_healthy
      registry-service:
        condition: service_healthy
      expense-db:
        condition: service_healthy


  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile

    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "--proxy=off", "http://localhost:9000/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 4

    ports:
      - "9000:9000"

    depends_on:
      config-server:
        condition: service_healthy
      registry-service:
        condition: service_healthy


  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile

    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "--proxy=off", "http://localhost:8085/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 4

    environment:
      EMAIL: kharief644@gmail.com
      PASSWORD: marson6277

    ports:
      - "8085:8085"

    depends_on:
      config-server:
        condition: service_healthy
      registry-service:
        condition: service_healthy

volumes:
  user_data:
  medical-record_data:
  expense_data:
  appointment_data: