spring:
  application:
    name: api-gateway

  config:
    uri: http://config-server:8888


server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka/