spring:
  application:
    name: expense-service

  config:
    import: optional:configserver:http://capstone-config-server:8888


server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://registry-service:8761/eureka/