spring:
  application:
    name: registry-service


  config:
    import: optional:configserver:http://capstone-config-server:8888

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false