server:
  port: 8888

spring:
  profiles:
    active: native


  config:
    import: optional:configserver:http://capstone-config-server:8888

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config