server:
  port: 9000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/

okta:
  oauth2:
    issuer: https://dev-69097809.okta.com/oauth2/default
    clientId: 0oahzn5rzss401QqG5d7
    clientSecret: yteZu5tt6dn7GPcdXDmKg3_NtbRH3nroqepSxf9RaYxolcbz0UDhP3dc-B49gvTq


  config:
    uri: http://config-server:8888


spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/patients/**, /api/v1/doctors/**

        - id: appointment-service
          uri: lb://appointment-service
          predicates:
            - Path=/api/v1/appointments/**

        - id: expense-service
          uri: lb://expense-service
          predicates:
            - Path=/api/v1/expenses/**

        - id: medical-record-service
          uri: lb://medical-record-service
          predicates:
            - Path=/api/v1/medical-record/**