server:
  port: 8084


eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/

okta:
  oauth2:
    issuer: https://dev-69097809.okta.com/oauth2/default
    clientId: 0oahzn5rzss401QqG5d7
    clientSecret: yteZu5tt6dn7GPcdXDmKg3_NtbRH3nroqepSxf9RaYxolcbz0UDhP3dc-B49gvTq


  config:
    import: optional:configserver:http://capstone-config-server:8888

spring:
  datasource:
    url: jdbc:postgresql://expense-db:5432/expense
    username: expense
    password: capstone
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

flyway:
  locations: classpath:db/migration