server:
  port: 8082


eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka/

okta:
  oauth2:
    issuer: https://dev-21108441.okta.com/oauth2/default
    clientId: 0oaaoqvokauMiS7dW5d7
    clientSecret: eM3xqDXzvlMeYQauObPtF0cqy_tabiGR3DcKOorMzweFiridO3r4GNsFNopoQUzi

spring:
  datasource:
    url: jdbc:postgresql://medical-record-db:5432/medical-record
    username: medical-record
    password: capstone
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

flyway:
  locations: classpath:db/migration